### ISSUE TITLE
Cleanup task

### ISSUE THREAD

**Issue by gbraad** [gbraad-actions/cleanup-untagged-packages#1]
```yaml
name: Cleanup untagged packages
description: "A simple action to remove untagged packages from the container registry"
author: "Gerard Braad <me@gbraad.nl>"
inputs:
  package:
    description: "Name of the container registry package"
    required: true
    type: string
  token:
    required: false
    type: string
    default: ${{ github.token }}
  owner:
    required: flase
    type: string
    default: ${{ github.user }}
runs:
runs:
  using: 'composite'
  steps:
    - name: Cleanup
      id: cleanup
      uses: actions/github-script@v3
      with:
        github-token: ${{ inputs.token}}
        script: |
          const response = await github.request("GET /${{ inputs.owner }}/packages/container/${{ inputs.package }}/versions",
            { per_page: ${{ env.PER_PAGE }}
          });
          for(version of response.data) {
            if (version.metadata.container.tags.length == 0) {
              console.log("delete " + version.id)
              const deleteResponse = await github.request("DELETE /${{ inputs.owner }}/packages/container/${{ inputs.package }}/versions/" + version.id, { });
              console.log("status " + deleteResponse.status)
            }
          }
      env:
        PER_PAGE: 100
```
